const NobleData = [
    {
        id:1,
        img:"1DmjGKz-rK1Ls9PqDnDadz3aFcjQKPLhR",
    },
    {
        id:2,
        img:"1Xpu8eYMH9sjMvbrI32WHgso5OTNRR_o7",
    },
    {
        id:3,
        img:"13SEbhre6WM_a9WZ4xFrs1ETu3tS5r4Ma",
    },
    {
        id:4,
        img:"1ssFZjCAoarpjIoornhy6Suf2KF3DW1DH",
    },
    {
        id:5,
        img:"1Ry6w6IO0zqVm9Qdtj277uvDcFOkFtuwJ",
    },
    {
        id:6,
        img:"1GDnu-JxsKca0TdAHbF8lLS1Qo2Bjzjjk",
    },
    {
        id:7,
        img:"1dvYeXOWS7xUtHy3tjZ5IzXj1QP8bfhqh",
    },
    {
        id:8,
        img:"1VzMqwxt600o8DISipMa-aVxcjyM4UkNu",
    },
    {
        id:9,
        img:"1P-ZZXtOOGgWJe3N0KpwL15JXWMDTIgsE",
    },
    {
        id:10,
        img:"16ddJjDxgw5gEKfwy2e26zJAGakRsC1jS",
    },
    {
        id:11,
        img:"1eYIXzl4FXzjyMGdGlxHse_-LsukvlyYE",
    },
];

export default NobleData;